palewire/news-homepages

.github/workflows/wisconsin.yml
bundles.csv
sources.csv

- Adds Wisco sources and adds Wisco bundle
- ~Adds New Mexico to bundles~
- ~Fixes New Mexico in sources so the bundle activates~

Adds Wisco publications

---

newshomepages/sources/javascript/sfchronicle.js
newshomepages/sources/sites.csv

add sfchronicle website

---

newshomepages/sources/javascript/vcstar.js

remove popup and ad

---

newshomepages/sources/javascript/usatoday.js

Issue 45/usatoday

---

newshomepages/sources/javascript/htrnews.js
newshomepages/sources/sites.csv

fix: remove popup and add for htrnews #36

---

newshomepages/sources/javascript/nationalpost.js

Adding the Javascript file to prevent popup from appearing in the screenshot for the national post site

---

newshomepages/sources/sites.csv

b901333 resolves #105, resolves #112 as well.

Add Miami Herald and Sac Bee again

---

newshomepages/sources/javascript/baltimoremag.js
newshomepages/sources/sites.csv

Remove modal for @Baltimoremag

---

newshomepages/sources/javascript/andscape.js

Ticket - [229](https://github.com/palewire/news-homepages/issues/229)
Added js to remove ads on [andscape.com](https://andscape.com/).

add js to remove ads on andscape.com

---

newshomepages/sources/javascript/laist.js

To remove campaign pop-up addressed in  Fix LAist #236

Created laist.js

---

newshomepages/sources/javascript/diariope.js
newshomepages/sources/javascript/fortunemagazine.js
newshomepages/sources/javascript/gridnews.js

Ticket - #[233](https://github.com/palewire/news-homepages/issues/233)
Ticket - #[232](https://github.com/palewire/news-homepages/issues/232)

add js to remove ads from diariope and fortune

---

newshomepages/screenshot.py
newshomepages/sources/javascript/citylimitsnews.js

The .Campaign can expect on other sites.

Add .Campaign to global list

---

newshomepages/sources/sites.csv

Add wait for @gridnews in site.csv

---

newshomepages/sources/javascript/gazettedotcom.js

Fix Cedar Rapids Gazette

---

newshomepages/sources/javascript/sowetanlive.js

Removes registration popup, GDPR banner, and chat widget from SowetanLive.

Remove popups and overlays from SowetanLive

---

newshomepages/tweet.py

If this is your biggest problem you're in great shape.

Handle thousands separator in tweet

---

newshomepages/sources/javascript/arthasarokar.js

Fixed Ads on  Artha Sarokar screenshot. fixes #297

fixed Artha Sarokar screenshot

---

newshomepages/sources/javascript/chicagotribune.js
newshomepages/sources/javascript/newshour.js
newshomepages/utils.py

* odds-and-ends: fixes some website's custom-javascript
* adds bundle to full-path-screenshot

added some small website fixes

---

extracts/csv/bundles.csv

Two that don't seem to fit this schema well: us-national and socal.

Add "type" to bundles file

---

newshomepages/utils.py

Blox blocks for aspendailynews and other sites.

Blox blocks.

---

newshomepages/sources/bundles.csv

This is what #335 was supposed to have done but I picked the wrong file to replace. Again.

Add "type" to bundles; add Idaho

---

newshomepages/wayback.py

Set a short timeout and longer backoff on the wayback.py post request

---

newshomepages/sources/bundles.csv

I swear that's the timezone name.

Stub  out Puerto Rico bundle

---

newshomepages/sources/sites.csv
newshomepages/utils.py

I seem to recall fixing this issue with infinite scroll webpages before, so I don't know what happened, whether somehow it got reverted. Anyway, I added gainesvilletimes.com and found out that infinite scrolling was going on... forever. 
So I pushed a small fix.
Alex

Fixed infinite scrolling issue and added gainesvilletimes.com

---

newshomepages/sources/javascript/nytimes.js

Add new JS to fix NYT popup

---

newshomepages/extract/robotstxt.py

- This restores the "latest" option to the download flags
- And it adds the archived URL to the table so that it is included in the outputted CSV

Fixes for the robotstxt extract command
